### ISSUE TITLE
Metric?

### ISSUE THREAD

**Issue by GDLForever** [mala-lab/TAM-master#2]
The metrics in the code appear to be AUROC and AP, not seen in the paper for AUPRC. Am I missing something? Thanks!

**Comment by fengduqianhe** [comment]
Hi, thanks for your questions, we found the mixed use of AUPRC and average precision especially on the imbalance dataset.  Generally, the two are the same by default. AP can be seen as an approximation of AUPRC

**Comment by GDLForever** [comment]
Thank you for your reply! However, I found that the number of nodes in Facebook（1081） did not match the description in the paper（4039）. May I ask why?

**Comment by fengduqianhe** [comment]
Hi thanks for your question, the dataset Facebook is obtained from https://github.com/zhiming-xu/conad, the statistical results are also obtained from the paper.  There seems to be a discrepancy in the statistics.
The main operation in our paper is to remove a very small number of isolated nodes in order to adapt to CoLA, SL-GAD，and TAM.
