### ISSUE TITLE
Amazon and Yelpchi

### ISSUE THREAD

**Issue by Ayachin3ne** [mala-lab/TAM-master#3]
Hello, I found that different treatments were applied to Amazon all, Amazon,  Yelpchi and Yelpchi all  in your experiment. However, the dataset args in your code only include Yelpchi and Amazon. Based on the running results, it appears that the large graph data of all was choosed. Which relationship was selected on the Amazon and Yelpchi small graph? Thanks!

**Comment by fengduqianhe** [comment]
Hi, thank you for the question, in the experiments,  we include Amazon all, Amazon (Amazon-UPU ), Yelpchi (YelpChi-RUR), and Yelpchi-all.    Amazon-UPU and Yelp-RUR are subsets of Amazon-all and Yelp respectively. Among them,  Amazon-UPU (connects the users who give reviews to at least one same product).  YelpChi-RUR (connects reviews posted by the same user)  are two small data sets with the same relation.  For these two datasets,  graph truncation depth to 4.   Amazon-all and YelpChi-all are two datasets by treating the different relations as a single relation.  Due to the increased number of nodes and edges, we set K = 7, for these two datasets based on this prior information.   There is only one type of edge in small Amazon and Yelp, which can be regarded as a homophily graph. In experiments, we found that TAM also works well for these heterophily graphs  (multiple types of edges) by treating them as a single type.

**Comment by Ayachin3ne** [comment]
> Hi, thank you for the question, in the experiments, we include Amazon all, Amazon (Amazon-UPU ), Yelpchi (YelpChi-RUR), and Yelpchi-all. Amazon-UPU and Yelp-RUR are subsets of Amazon-all and Yelp respectively. Among them, Amazon-UPU (connects the users who give reviews to at least one same product). YelpChi-RUR (connects reviews posted by the same user) are two small data sets with the same relation. For these two datasets, graph truncation depth to 4. Amazon-all and YelpChi-all are two datasets by treating the different relations as a single relation. Due to the increased number of nodes and edges, we set K = 7, for these two datasets based on this prior information. There is only one type of edge in small Amazon and Yelp, which can be regarded as a homophily graph. In experiments, we found that TAM also works well for these heterophily graphs (multiple types of edges) by treating them as a single type.

Thanks!
